enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

patches-version = "dev"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"

patcher-args = """\
  -OdarkThemeBackgroundColor=#FF111111 \
  -OlightThemeBackgroundColor=#FFF9F9F9 \
"""

[YouTube-Extended]
app-name = "YouTube"
rv-brand = "ReVanced Extended"
build-mode = "module"
version = "19.30.39"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom header for YouTube' 'Custom package name'"
included-patches = "'Visual preferences icons for YouTube' 'Return YouTube Username'"

[YouTube-Music-Extended]
app-name = "YouTube Music"
rv-brand = "ReVanced Extended"
build-mode = "module"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Custom header for YouTube Music' 'Custom package name'"
included-patches = "'Visual preferences icons for YouTube Music' 'Return YouTube Username'"
