enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

patches-version = "dev"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "module"
included-patches = "'Enable slide to seek'"
